version: '3'

services:
  api:
    build: .
    volumes:
      - .:/app
      - ./settings.py:/settings.py
    ports:
      - 12000:5000
    depends_on:
      - redis
    command: ['flask', 'run', '--host', '0.0.0.0']
    environment:
      # Always display output. By default, stdout is buffered and in
      # development we might lose messages.
      PYTHONUNBUFFERED: 1
      API_SETTINGS: /settings.py
      FLASK_DEBUG: 1

  redis:
    image: redis

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ['flask', 'rq', 'worker']
    environment:
      FLASK_APP: minimal_operateur_server.api
