__author__ = 'Vincent Lara'
__contact__ = 'vincent.lara@data.gouv.fr'
__homepage__ = 'https://github.com/openmaraude/minimal_operateur_server'
__version__ = '0.1.0'
__doc__ = 'Development server of APITaxi operator'
