__author__ = 'Julien Castets'
__contact__ = 'julien.castets@beta.gouv.fr'
__homepage__ = 'https://github.com/openmaraude/minimal_operateur_server'
__version__ = '0.1.0'
__doc__ = 'APITaxi operator server example'
